n1 = str(input("Insira um nome: ")).strip()
print("Esse nome em minúsculas é {}!".format(n1.lower()))
print("Esse nome em maiúsculas é {}!".format(n1.upper()))
print("Esse nome contém {} letras!".format(len(n1)-n1.count(" ")))
print("O primeiro nome tem {} letras!".format(n1.find(" ")))
Separa = n1.split()
print("O primeiro nome é {} e ele tem {} letras!".format(Separa[0],len(Separa[0])))

Nome = str(input("Insira um nome: ")).strip()
print("O nome em minúsculas fica {}!".format(Nome.lower()))
print("O nome em maiúsculas fica {}!".format(Nome.upper()))
print("O nome contém {} letras!".format(len(Nome) - Nome.count(" ")))
print("O primeiro nome contém {} letras!".format(Nome.find(" ")))

n1 = str(input("Insira um nome: ")).strip()
n2 = str(input("Insira um outro nome: ")).strip()
print("Os nomes em minúsculas ficam {} e {}!".format(n1.lower(),n2.lower()))
print("Os nomes em maiúsculas ficam {} e {}!".format(n1.upper(),n2.upper()))
print("Os nomes tem {} e {} letras no total, respectivamente!".format(len(n1)-n1.count(" "),len(n2)-n2.count(" ")))
print("Os primeiros nomes possem {} e {} letras no total!".format(n1.find(" "),n2.find(" ")))

num = int(input("Insira um número: "))
n = str(num)
print("Analisando o número {} insirido...".format(num))
print("Unidade: {}".format(n[3]))
print("Dezena: {}".format(n[2]))
print("Centena: {}".format(n[1]))
print("Milhar: {}".format(n[0]))

num = int(input("Insira um núemro de casas milhares: "))
print("Analisando o núemro {}...".format(num))
print("Sua unidade é {}!".format(num // 1 % 10))
print("Sua dezena é {}!".format(num // 10 % 10))
print("Sua cntena é {}!".format(num // 100 % 10))
print("Seu milhar é {}!".format(num // 1000 % 10))

num1 = int(input("Insira um número: "))
num2 = int(input("Insira outro número: "))
print("Analizando o número {} e o número {}...".format(num1,num2))
print("Suas respectivas unidades são {} e {}!".format(num1 // 1 % 10,num2 // 1 % 10))
print("Suas repectivas dezenas são {} e {}!".format(num1 // 10 % 10,num2 // 10 % 10))
print("Suas repectivas centenas são {} e {}!".format(num1 // 100 % 10,num2 // 100 % 10))
print("Seus repectivos milhares são {} e {}!".format(num1 // 1000 % 10,num2 // 1000 % 10))
